/* Bake api/_prompt.js — her offline fallback mind — from PROMPT/*.md.
   api/_mind.js streams the real prompt from GitHub on every request and only reads this file
   when that fetch fails, but it `require`s it at import time, so it must exist for the
   functions to load at all. It is committed for that reason.

       node scripts/assemble-prompt.js

   Re-run it whenever you change PROMPT/*.md or PROMPT/VERSION. A stale fallback is the worst
   kind of bug — rare, silent, and only ever visible when GitHub is already down.
   The assembly order and dividers below MUST stay identical to refresh() in api/_mind.js. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = (f) => fs.readFileSync(path.join(ROOT, 'PROMPT', f), 'utf8').trim();

const core = read('PROMPT-CORE.md');
const skills = read('SKILLS.md');
const know = read('KNOWLEDGE.md');
const V = read('VERSION').split('\n')[0].trim();

const full = core + '\n\n' + '='.repeat(8) + ' SKILLS REGISTRY ' + '='.repeat(8) + '\n\n' + skills
  + '\n\n' + '='.repeat(8) + ' DASH KNOWLEDGE PACK ' + '='.repeat(8) + '\n\n' + know;

const out = '/* AUTO-GENERATED by scripts/assemble-prompt.js from PROMPT/*.md — do not edit. */\n'
  + 'const SYSTEM_PROMPT = ' + JSON.stringify(full) + ';\n'
  + 'const VERSION = ' + JSON.stringify(V) + ';\n'
  + 'module.exports = { SYSTEM_PROMPT, VERSION };\n';

fs.writeFileSync(path.join(ROOT, 'api', '_prompt.js'), out);
console.log('baked api/_prompt.js — ' + full.length + ' chars, version ' + V);
