/* X (Twitter) client — OAuth 1.0a user-context signing, zero dependencies.
   Reads can use the app-only Bearer; POSTing a reply REQUIRES user context
   (X_ACCESS_TOKEN + X_ACCESS_SECRET generated by the account that posts). */
const crypto = require('crypto');

const API = 'https://api.x.com';
const enc = (s) => encodeURIComponent(String(s)).replace(/[!*()']/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase());

function oauthHeader(method, url, params, extraOauth) {
  const ck = process.env.X_CONSUMER_KEY, cs = process.env.X_CONSUMER_SECRET;
  const at = process.env.X_ACCESS_TOKEN, as = process.env.X_ACCESS_SECRET;
  if (!ck || !cs || !at || !as) return null;
  const o = Object.assign({
    oauth_consumer_key: ck,
    oauth_nonce: crypto.randomBytes(16).toString('hex'),
    oauth_signature_method: 'HMAC-SHA1',
    oauth_timestamp: Math.floor(Date.now() / 1000).toString(),
    oauth_token: at,
    oauth_version: '1.0',
  }, extraOauth || {});
  /* signature base: every oauth_* param + every query param, sorted */
  const all = Object.assign({}, o, params || {});
  const base = Object.keys(all).sort().map((k) => enc(k) + '=' + enc(all[k])).join('&');
  const sigBase = method.toUpperCase() + '&' + enc(url) + '&' + enc(base);
  const signingKey = enc(cs) + '&' + enc(as);
  o.oauth_signature = crypto.createHmac('sha1', signingKey).update(sigBase).digest('base64');
  return 'OAuth ' + Object.keys(o).sort().map((k) => enc(k) + '="' + enc(o[k]) + '"').join(', ');
}

/* ---- reads. Most work app-only; DM endpoints refuse app-only auth and require the user
       context (403 "Unsupported Authentication"), so pass {user:true} for those. ---- */
async function xGet(path, query, opts) {
  const bearer = process.env.X_BEARER_TOKEN;
  const qs = query ? ('?' + Object.keys(query).map((k) => k + '=' + encodeURIComponent(query[k])).join('&')) : '';
  const url = API + path + qs;
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), 15000);
  try {
    /* X issues the bearer already percent-encoded — pass it VERBATIM. Decoding it → 401. */
    let auth = (opts && opts.user) ? null : (bearer ? ('Bearer ' + bearer.trim()) : null);
    if (!auth) auth = oauthHeader('GET', API + path, query || {});
    if (!auth) throw new Error('no X user credentials configured (DM endpoints require them)');
    const r = await fetch(url, { signal: ctl.signal, headers: { Authorization: auth } });
    const d = await r.json();
    if (!r.ok) throw new Error('x GET ' + path + ' → ' + r.status + ' ' + JSON.stringify(d).slice(0, 200));
    return d;
  } finally { clearTimeout(t); }
}

/* ---- writes: prefer OAuth 1.0a user context — those tokens NEVER EXPIRE, which is what an
       unattended bot needs. Fall back to the OAuth 2.0 user token (2h life) only if no
       static OAuth1 tokens are installed. JSON body is not part of the OAuth1 signature. ---- */
async function xPost(path, body) {
  const url = API + path;
  let auth = oauthHeader('POST', url, {});
  if (!auth) {
    const o2 = process.env.X_OAUTH2_ACCESS;
    auth = o2 ? ('Bearer ' + o2.trim()) : null;
  }
  if (!auth) return { error: 'X posting is not configured — no OAuth1 access token/secret and no OAuth2 user token (an app-only Bearer cannot post).' };
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), 20000);
  try {
    const r = await fetch(url, {
      method: 'POST', signal: ctl.signal,
      headers: { Authorization: auth, 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    const d = await r.json();
    if (!r.ok) return { error: 'x POST ' + path + ' → ' + r.status + ' ' + JSON.stringify(d).slice(0, 300) };
    return d;
  } catch (e) {
    return { error: 'x POST failed: ' + e.message };
  } finally { clearTimeout(t); }
}

const whoCache = { at: 0, user: null };
async function botUser() {
  if (whoCache.user && Date.now() - whoCache.at < 6 * 36e5) return whoCache.user;
  const handle = (process.env.X_HANDLE || '').replace(/^@/, '').trim();
  if (!handle) throw new Error('X_HANDLE not set');
  const d = await xGet('/2/users/by/username/' + handle);
  if (!d || !d.data) throw new Error('handle @' + handle + ' not found on X');
  whoCache.at = Date.now(); whoCache.user = d.data;
  return d.data;
}

/* Split a reply into a thread that NEVER loses a character.
   The old version capped at 4 tweets and folded the remainder into the last one with a
   slice() — which silently ate everything past ~1080 chars. Nothing here truncates: the
   packer consumes tokens until there are none left, and the thread is however long the
   answer needs. Line breaks are preserved and breaks prefer paragraph > sentence > word.

   X measures length its own way: every URL counts as 23 characters no matter how short,
   so a naive .length can under-count and get a tweet rejected at 280. xLen() mirrors that. */
const MAX_TWEETS = 25;                       // runaway guard only — a real answer never nears it
const URL_RE = /(https?:\/\/[^\s]+)|(\bwww\.[^\s]+)|(\b[a-z0-9-]+\.(?:com|org|io|dev|net|team|xyz|ai|co|app)(?:\/[^\s]*)?)/gi;
function xLen(s) { return String(s).replace(URL_RE, 'xxxxxxxxxxxxxxxxxxxxxxx').length; }

function sanitize(text) {
  return String(text)
    .replace(/```[\s\S]*?```/g, ' (code in the Dash Support Team chat) ')   // fences read as junk on X
    .replace(/^#{1,6}\s*/gm, '')                                            // markdown headers
    .replace(/\*\*([^*]+)\*\*/g, '$1').replace(/(^|\s)\*([^*\n]+)\*/g, '$1$2')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/^\s*[-*]\s+/gm, '· ')                                         // bullets X won't render
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function thread(text, hard) {
  const HARD = hard || 280;
  const RESERVE = 7;                          // room for the " 10/12" counter
  const lim = HARD - RESERVE;
  const clean = sanitize(text);
  if (xLen(clean) <= HARD) return [clean];

  /* Keep the separators so paragraph breaks survive into the tweets. Any single token
     longer than one tweet (a hash, a giant URL, a wall with no spaces) is hard-wrapped
     into several tokens FIRST — otherwise the packer can't break it and would emit an
     oversize tweet that X rejects. Wrapping adds tweets; it never removes characters. */
  const toks = [];
  clean.split(/(\s+)/).forEach(function (t) {
    if (/^\s*$/.test(t) || xLen(t) <= lim) { toks.push(t); return; }
    let s = t;
    while (xLen(s) > lim) {
      let cut = Math.min(lim, s.length);
      while (cut > 1 && xLen(s.slice(0, cut)) > lim) cut--;
      toks.push(s.slice(0, cut));
      toks.push('');                 // a seam the packer may break on, costing no whitespace
      s = s.slice(cut);
    }
    if (s) toks.push(s);
  });
  const parts = [];
  let cur = '';
  for (let i = 0; i < toks.length; i++) {
    const tok = toks[i];
    const next = cur + tok;
    if (xLen(next) > lim && cur.trim()) {
      parts.push(cur.trim());
      cur = /^\s+$/.test(tok) ? '' : tok;     // don't start a tweet with the old whitespace
      if (parts.length >= MAX_TWEETS - 1) {   // pathological length: bail into one last part
        cur += toks.slice(i + 1).join('');
        break;
      }
      continue;
    }
    /* Break where a reader would: at a paragraph, or at the end of a sentence once the
       tweet is substantial. Mid-sentence breaks are legal but read like a dropped call. */
    if (/^\s+$/.test(tok) && cur.trim()) {
      const isPara = /\n\n/.test(tok);
      const endsSentence = /[.!?][")'”]?$/.test(cur.trim());
      if ((isPara && xLen(cur) > lim * 0.45) || (endsSentence && xLen(cur) > lim * 0.62)) {
        parts.push(cur.trim());
        cur = '';
        continue;
      }
    }
    cur = next;
  }
  if (cur.trim()) parts.push(cur.trim());

  /* fold an orphan tail back into the previous tweet — nobody wants a "and that's it. 5/5" */
  while (parts.length > 1) {
    const last = parts[parts.length - 1];
    const prev = parts[parts.length - 2];
    const merged = prev + ' ' + last;
    if (xLen(last) < lim * 0.2 && xLen(merged) <= lim) {
      parts.splice(parts.length - 2, 2, merged);
    } else break;
  }

  const n = parts.length;
  if (n === 1) return parts;            // pre-wrapping guarantees this one already fits
  return parts.map(function (p, i) { return p + ' ' + (i + 1) + '/' + n; });
}

module.exports = { xGet, xPost, botUser, thread };
